version: '3.4'

services:
  losecoupledmonolithic.server:
    image: ${DOCKER_REGISTRY-}losecoupledmonolithicserver
    depends_on: 
        - postgresql
    links:
        - postgresql
    build:
      context: .
      dockerfile: LoseCoupledMonolithic.Server/Dockerfile

  postgresql:
    image: postgres
    container_name: postgres-stubb
    ports:
        - "5432:5432"       
    environment:         
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    restart: always

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "6500:80"